### PR TITLE
Feature/settings to single feed

### PR DESCRIPTION
**Pull request by doekenorg**
MR that creates a new base add-on that's based on the feed add-on; like all the other add-ons. 

I've cleaned up the code quite a bit by removing a lot of inline HTML & JS to separate fields and files.

Since this will be a 2.0 version there are many breaking changes and code clean ups to WP standards.

- [x] Create a new add on
- [x] Migrate add settings 
- [x] Migrate form settings to new feed settings
- [x] Remove deprecation warnings + introduced the breaking changes
- [x] Migrate the left over inline JS to a file.
- [x] Restore bulk actions
- [x] Add some missing styling for settings pages
- [x] Remove the old add-on completely
- [x] Fix some `Todos:` 
- [x] Fix attachment being send
- [x] Fix sections-hook (possibly incorrect array-depth)
- [x] Refresh settings page after enabling / disabling the feed
- [x] Migrate styling over (disabled because the original add on is not running anymore)
- [x] Quick links
- [x] Meta boxes
- [x] Duplicate feed settings on form duplication

## Things changed
- `GFExcelAdmin` no longer exists, apart from a `class_alias` to satisfy the addons that rely on it. 
- `GravityExportAddon` is the new (better named) single FEED add on
- All custom fields have been promoted to actual GravityForm Fields in `src/GravityForms/Fields` (download section, download url section, sortable fields)
- All inline javascript has been removed from the add on and placed inside the proper files (and fields).
- A migration moves all the old data (field names) to the new feed settings
- A lot of logic has been moved to separate files through the `Component` section.

So the Add on is way cleaner, and only contains logic for the add on. The rest is moved to files and classes responsible for that one thing. These fields should be reusable in next versions of the pro add-ons. This eliminates duplication, and a single source for updates.

Please make sure to test: 

- Migrating old settings to the new section; I feel this could be error-prone; although it worked. (Updating the plugin from an old version to the next should trigger this migration)
- Duplicating forms with the feed
- Downloading, filtering, etc
- The PRO add-ons should still works of course
- Meta boxes on the download
- Bulk downloads from the form list
- short tags

### CODE REVIEW

**Comment by doekenorg** [comment]
Can't remove `GFExcelAdmin` until all the Pro plugins are updated. So for now I'm porting some stuff over to a new `GFExcelAdmin` and let the new addon extend from that. Should keep everything working until everything is updated.

**Comment by doekenorg** [comment]
Renamed the new plugin to `gravityexport-lite` but that will break some of the pro add-ons, because they want the `gf-entries-in-excel` add-on as a dependency.

**Comment by doekenorg** [comment]
Bulk action restored. Really annoyed by some choices GF made on `private` vs `protected`.

**Comment by doekenorg** [comment]
- [ ] Check on `gform_export_fields` from current plugin.

**Comment by rafaehlers** [comment]
- [ ] I got the message below on the dashboard when the plugin is activated on PHP 8.1 (and twice if GravityExport "PRO" is also activated)
>Deprecated: dirname(): Passing null to parameter #1 ($path) of type string is deprecated in /home/jerofiyumi9346/web/gravityexport.try.gravitykit.com/public_html/wp-content/plugins/gravityforms/includes/addon/class-gf-addon.php on line 6203

https://gravityexport.try.gravitykit.com/wp-admin/?page=gf_edit_forms&view=settings&subview=gf-entries-in-excel&id=1

I couldn't test notification attachments, that website is not sending emails.

**Comment by doekenorg** [comment]
> * [x]  I got the message below on the dashboard when the plugin is activated on PHP 8.1 (and twice if GravityExport "PRO" is also activated)

I fixed this on `develop`. Was missing a `$_path`.

**Pull request merged**
